Support I18n 1.10.0
This upgrades the logic to support the I18n 1.10.0 release, that was
broking with issue like:

```
LoadError: cannot load such file -- i18n/core_ext/hash
```

or
```
NameError: uninitialized constant I18n::HashRefinements
```

The I18n internal hash structure also changed sightly, so this fix
accomodates that.

Deprecated Ruby versions (< 2.7) are also removed for good measure.

Related I18n issue:
- https://github.com/ruby-i18n/i18n/pull/602